owner                  = "tdupoiron"
aws_region             = "eu-west-3"
aws_availability_zones = ["eu-west-3a", "eu-west-3b", "eu-west-3c"]
ovh_region             = "ovh-eu"
ovh_domain             = "dupoiron.com"
webapp_subdomain       = "nexus"
webapp_name            = "nexus"
webapp_image           = "sonatype/nexus3:latest"
webapp_port            = 8081