name: Deploy Nexus

on:
  workflow_dispatch:

env:
  domain: dupoiron.com
  TF_VAR_webapp_subdomain: nexus
  TF_VAR_webapp_name: nexus
  TF_VAR_webapp_image: sonatype/nexus3
  TF_VAR_webapp_port: 8081

jobs:
  terraform:
    runs-on: ubuntu-latest

    outputs:
      terraform_output: ${{ steps.deploy.outputs.terraform_output }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform apply
        id: deploy
        run: | 
          terraform init -backend-config=backend.conf
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan
          terraform output -json > terraform_output.json
          echo "terraform_output=$(cat terraform_output.json)" >> "$GITHUB_OUTPUT"
        env:
          OVH_APPLICATION_KEY: ${{ secrets.OVH_APPLICATION_KEY }}
          OVH_APPLICATION_SECRET: ${{ secrets.OVH_APPLICATION_SECRET }}
          OVH_CONSUMER_KEY: ${{ secrets.OVH_CONSUMER_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  summary:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Summary
        run: |
          echo "Terraform output: ${{ needs.terraform.terraform_output }}" >> "$GITHUB_STEP_SUMMARY"
          echo "Application URL: http://${{ env.TF_VAR_webapp_subdomain }}.${{ env.domain }}" >> "$GITHUB_STEP_SUMMARY"
